# Generated by Django 5.1.7 on 2025-04-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('chef', 'Chef'), ('customer', 'Customer')], default=None, max_length=10, null=True),
        ),
    ]
