# Create render.yaml in project root
services:
  - type: web
    name: recipe-catalog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn recipe_catalog.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://recipe_catalog_user:agpYxSM3DSr7DmSbyyR6xJTEX8q0gNU5@dpg-d0gh4fqdbo4c73bd3mgg-a/recipe_catalog
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: recipe_catalog.settings.production
    plan: free

databases:
  - name: recipe-db
    plan: free
    databaseName: recipe_db
    user: recipe_user