# Generated by Django 5.1.7 on 2025-04-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_alter_meal_recipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('day', 'meal_type')},
        ),
    ]
